### PR TITLE
Set minimum required Python version to 3.6

### PR DESCRIPTION
**Pull request by falzm**
This change restricts the minimum Python version requirement to 3.6.

### CODE REVIEW

**Comment by greut** [comment]
fun fact, it does not.

**Comment by zyegfryed** [comment]
@greut do you imply we should go further and use [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) and/or [check the Python version in `setup.py`](https://stackoverflow.com/a/19535016)?

**Comment by greut** [comment]
`python_requires` would indeed restrict the minimum version.

**Comment by zyegfryed** [comment]
@greut Fixed in [6b590d6].

**Pull request merged**
