### PR TITLE
Make API classmethods protected

### PR DESCRIPTION
**Pull request by falzm**
Hide API `classmethod` functions from the public API to avoid users
being tempted to use them directly.

### CODE REVIEW

**Comment by exo-cedric** [comment]
Wouldn't a single underscore mean the methods are _protected_ rather than _private_ ?

**Comment by falzm** [comment]
> Wouldn't a single underscore mean the methods are _protected_ rather than _private_ ?

You're right, I didn't know there was different meanings depending on the number of `_`s. I'll change to `__`.

**Comment by falzm** [comment]
So, turns out that when I switch previously *protected* methods to *private* nothing works anymore:

```python
>>> import exoscale
>>> exo = exoscale.Exoscale(trace=False)
>>> gva2 = exo.compute.get_zone("ch-gva-2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marc/Documents/Exoscale/git/python-exoscale/exoscale/api/compute.py", line 2266, in get_zone
    zones = list(self.list_zones(id=id, name=name))
  File "/Users/marc/Documents/Exoscale/git/python-exoscale/exoscale/api/compute.py", line 2246, in list_zones
    yield Zone.__from_cs(i)
AttributeError: type object 'Zone' has no attribute '_ComputeAPI__from_cs'
```

**Comment by falzm** [comment]
I though this was a matter of convention, but turns out it seems to be actually changing the behavior of the interpreter ¯\\\_(ツ)_/¯

**Comment by exo-cedric** [comment]
So maybe _Make API classmethods **protected**_ is fine given your original post ?

**Comment by falzm** [comment]
> So maybe _Make API classmethods **protected**_ is fine given your original post ?

Let's say it is ;)

**Comment by jgrondier** [comment]
@falzm you want double leading *and* trailing underscores

**Comment by falzm** [comment]
> @falzm you want double leading _and_ trailing underscores

Yes you're right, after a bit of digging in this direction it would be the "right" thing to do but pragmatically the single leading underscore should be enough to signal the library users.

**Comment by falzm** [comment]
This article is very useful: https://dbader.org/blog/meaning-of-underscores-in-python

**Comment by falzm** [comment]
> Don't forget to rename the commit :)

Yep, I'll fix the commit message at merge time ;)

**Comment by falzm** [comment]
Integration tests passed OK ✅

**Pull request merged**
